In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else :
  print("GPU not available. Using CPU ")

GPU is available!
Using GPU: Tesla T4


CREATING TENSORS

In [3]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[1.8877e-01, 4.4271e-41, 1.8877e-01],
        [4.4271e-41, 7.0976e+22, 2.1715e-18]])


In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.6279, 0.2416, 0.9716],
        [0.0648, 0.3200, 0.5147]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.4273, 0.3981, 0.7337],
        [0.1859, 0.7037, 0.9208]])

In [9]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3] , [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

#  arange
print("using arange -> ", torch.arange(0,10)) # we can pas step here as well

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->" , torch.full((3,5) , 5))

using arange ->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])


Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x) #It basically creates the vector of same shape as that of x

tensor([[    135691946249600,     135691946249600, 4661726013461248228],
        [4681742012764214613,                  48,                 128]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
# assign data type
torch.tensor([1,2,3], dtype = torch.float)

tensor([1., 2., 3.])

In [22]:
# using to

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical Operationns

1. Scaler Operation

In [23]:
x = torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [24]:
# addition

x + 2
# substraction
x - 2
# # multiplication
x * 3
# division
x/3

# int division
(x * 100)//2

#  mod
(x * 100)%2

# power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

In [25]:
# Element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [26]:
# addition

a + b
# substraction
a - b
# # multiplication
a * b
# division
a / b


# power
a ** b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [27]:
c = torch.tensor([1,-2,3,-4])

In [28]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
# round
d = torch.tensor([1.2,1.5,1.8])
torch.round(d)

tensor([1., 2., 2.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 2., 2.])

In [32]:
# floor
torch.floor(d)

tensor([1., 1., 1.])

In [33]:
# clamp
torch.clamp(d, min = 1.3, max = 1.7)

tensor([1.3000, 1.5000, 1.7000])

Reduction operation

In [34]:
e = torch.randint(size = (2,3), high = 10, dtype = torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [35]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim = 0)
# sum along rows
torch.sum(e, dim = 1)

tensor([ 7., 21.])

In [36]:
# mean
torch.mean(e)
# mean along columns
torch.mean(e, dim = 0)
# mean along rows
torch.mean(e, dim = 1)

tensor([2.3333, 7.0000])

In [37]:
# median
torch.median(e)
# median along columns
torch.median(e, dim = 0)
# median along rows
torch.median(e, dim = 1)

torch.return_types.median(
values=tensor([0., 7.]),
indices=tensor([2, 2]))

In [38]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [39]:
# product
torch.prod(e)
# product along columns
torch.prod(e, dim = 0)
# product along rows
torch.prod(e, dim = 1)

tensor([  0., 315.])

In [40]:
# standard deviation
torch.std(e)
# standard deviation along columns
torch.std(e, dim = 0)
# standard deviation along rows
torch.std(e, dim = 1)

tensor([4.0415, 2.0000])

In [41]:
# variance
torch.var(e)
# variance along columns
torch.var(e, dim = 0)
# variance along rows
torch.var(e, dim = 1)

tensor([16.3333,  4.0000])

In [42]:
# argmax -> tells the position of maxm element
torch.argmax(e)
# argmax along columns
torch.argmax(e, dim = 0)
# argmax along rows
torch.argmax(e, dim = 1)

tensor([0, 0])

In [43]:
# argmin -> tells the position of minm element
torch.argmin(e)
# argmin along columns
torch.argmin(e, dim = 0)
# argmin along rows
torch.argmin(e, dim = 1)

tensor([1, 1])

Matrix Operations

In [44]:
f = torch.randint(size = (2,3), high = 10)
g = torch.randint(size = (3,2), high = 10)
print(f)
print(g)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [45]:
# matrix multiplication
torch.matmul(f,g)

tensor([[116, 126],
        [ 80,  98]])

In [46]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])
# dot product
torch.dot(vector1, vector2)

tensor(32)

In [47]:
# transpose
torch.transpose(f , 0 , 1)

tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [48]:
h = torch.randint(size = (3,3),low = 0, high = 10, dtype = torch.float32)
h

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [49]:
# determinant
torch.det(h)

tensor(-135.0000)

In [50]:
# inverse
torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

5. Comparision Operations

In [51]:
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)
print(i)
print(j)

tensor([[3, 6, 1],
        [5, 5, 0]])
tensor([[4, 3, 8],
        [8, 3, 3]])


In [52]:
# greater than
i > j
# less than
i < j
#  equal to
i == j
# not equal to
i != j
# greater than or equal
i >= j
# less than or equal
i <= j

tensor([[ True, False,  True],
        [ True, False,  True]])

6. Special functions

In [53]:
k = torch.randint(size = (2,3), low = 0, high = 10, dtype=torch.float32)
k

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [54]:
# log
torch.log(k)

tensor([[1.6094,   -inf, 1.7918],
        [1.3863,   -inf, 2.0794]])

In [55]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [5.4598e+01, 1.0000e+00, 2.9810e+03]])

In [56]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.4495],
        [2.0000, 0.0000, 2.8284]])

In [57]:
#  sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9975],
        [0.9820, 0.5000, 0.9997]])

In [58]:
# softmax
torch.softmax(k, dim = 0)

tensor([[0.7311, 0.5000, 0.1192],
        [0.2689, 0.5000, 0.8808]])

In [59]:
# relu
torch.relu(k)

tensor([[5., 0., 6.],
        [4., 0., 8.]])

INplace Operations

In [60]:
m = torch.randint(size = (2,3), low = 0, high = 10, dtype=torch.float32)
n = torch.randint(size = (2,3), low = 0, high = 10, dtype=torch.float32)
print(m)
print(n)

tensor([[4., 7., 2.],
        [3., 8., 5.]])
tensor([[6., 2., 9.],
        [5., 0., 4.]])


In [61]:
m + n # creates a new tensor that stores thd value of m + n

tensor([[10.,  9., 11.],
        [ 8.,  8.,  9.]])

In [62]:
m.add_(n) #value of n gets added to m and is stored inside m

tensor([[10.,  9., 11.],
        [ 8.,  8.,  9.]])

In [63]:
m

tensor([[10.,  9., 11.],
        [ 8.,  8.,  9.]])

In [64]:
n

tensor([[6., 2., 9.],
        [5., 0., 4.]])

In [65]:
torch.relu(m)

tensor([[10.,  9., 11.],
        [ 8.,  8.,  9.]])

In [66]:
m.relu_()

tensor([[10.,  9., 11.],
        [ 8.,  8.,  9.]])

In [67]:
m

tensor([[10.,  9., 11.],
        [ 8.,  8.,  9.]])

Copying a Tensor

In [68]:
a = torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [69]:
b = a

In [70]:
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [71]:
a[0][0] = 0.5
a

tensor([[0.5000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [72]:
b # changes made in a is reflected in b

tensor([[0.5000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [73]:
id(a)

135687540827760

In [74]:
id(b)

135687540827760

In [75]:
b = a.clone() # this will create a new tensor with same val and dimension and  b will point to it
print(a)
print(b)

tensor([[0.5000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])
tensor([[0.5000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])


In [76]:
a[0][0]= 10
a

tensor([[10.0000,  0.7668,  0.1659],
        [ 0.4393,  0.2243,  0.8935]])

In [77]:
b

tensor([[0.5000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [78]:
id(a)

135687540827760

In [79]:
id(b)

135687540868912

Tensor Operations on GPU

In [80]:
torch.cuda.is_available()

True

In [83]:
device =torch.device('cuda')
device

device(type='cuda')

In [84]:
# Creating a new temsor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [86]:
# moving an existing tensor to GPU
a

tensor([[10.0000,  0.7668,  0.1659],
        [ 0.4393,  0.2243,  0.8935]])

In [88]:
b = a.to(device)

In [89]:
b

tensor([[10.0000,  0.7668,  0.1659],
        [ 0.4393,  0.2243,  0.8935]], device='cuda:0')

In [95]:
import time
# Define size of the matrices
size = 1000 #large size for performance comparision


# Create random matrices on CPU
matrix_a = torch.rand(size, size)
matrix_b = torch.rand(size, size)

# Measure time taken to perform matrix multiplication on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_a, matrix_b) # matrix multiplication on CPU
end_time = time.time()
time_taken_cpu = end_time - start_time

print(f"Time on CPU: {time_taken_cpu:.4f} seconds")

# Move matrices to GPU
matrix_a = matrix_a.to('cuda')
matrix_b = matrix_b.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_a, matrix_b) # matrix multiplication on GPU
torch.cuda.synchronize()  # Wait for the GPU operation to complete
end_time = time.time()
time_taken_gpu = end_time - start_time
print(f"Time on GPU: {time_taken_gpu:.4f} seconds")

# compare Result
print("\n Speedup (CPU time / GPU time) : ", time_taken_cpu/time_taken_gpu)

Time on CPU: 0.0309 seconds
Time on GPU: 0.0011 seconds

 Speedup (CPU time / GPU time) :  27.738105443634804


Reshaping Tensors

In [96]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [97]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [98]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
b = torch.rand(2,3,4)
b

tensor([[[0.6858, 0.9301, 0.2309, 0.3430],
         [0.4687, 0.9974, 0.3924, 0.7481],
         [0.6762, 0.9614, 0.3290, 0.0964]],

        [[0.8724, 0.8935, 0.1608, 0.0670],
         [0.2026, 0.6516, 0.3711, 0.4893],
         [0.8173, 0.9066, 0.5195, 0.1399]]])

In [100]:
b.shape

torch.Size([2, 3, 4])

In [103]:
c = b.permute(2,1,0)
c

tensor([[[0.6858, 0.8724],
         [0.4687, 0.2026],
         [0.6762, 0.8173]],

        [[0.9301, 0.8935],
         [0.9974, 0.6516],
         [0.9614, 0.9066]],

        [[0.2309, 0.1608],
         [0.3924, 0.3711],
         [0.3290, 0.5195]],

        [[0.3430, 0.0670],
         [0.7481, 0.4893],
         [0.0964, 0.1399]]])

In [104]:
c.shape

torch.Size([4, 3, 2])

In [108]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
print(c.shape)

c.unsqueeze(0).shape # basically adding a dimension at given place

torch.Size([226, 226, 3])


torch.Size([1, 226, 226, 3])

In [110]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and Pytorch

In [111]:
import numpy as np

In [112]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [114]:
b = a.numpy()
b

array([1, 2, 3])

In [115]:
type(b)

numpy.ndarray

In [118]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [119]:
torch.from_numpy(c)

tensor([1, 2, 3])