In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0] , test_size=0.2)

In [7]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
x_train

array([[-0.66319191, -1.2380063 , -0.71708323, ..., -0.47803166,
         0.35679681, -0.91090137],
       [ 0.44666314,  0.88402458,  0.76548428, ...,  2.01257502,
         0.64374209,  0.95716786],
       [ 0.05878013, -0.59076376, -0.0549577 , ..., -1.23405967,
        -0.69153166, -1.21388918],
       ...,
       [ 0.56274492,  0.06341351,  0.51399202, ...,  0.57586253,
        -0.37850045, -1.07146357],
       [-0.13940827,  0.56964963, -0.18441437, ..., -0.79847041,
        -0.71109611, -0.73166914],
       [-0.85571778, -0.52141635, -0.84035567, ..., -0.29135055,
        -0.16655224,  1.75197744]])

In [9]:
y_train

281    B
258    M
270    B
241    B
162    M
      ..
317    M
457    B
75     M
267    B
507    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,

In [12]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
x_train_tensor

tensor([[-0.6632, -1.2380, -0.7171,  ..., -0.4780,  0.3568, -0.9109],
        [ 0.4467,  0.8840,  0.7655,  ...,  2.0126,  0.6437,  0.9572],
        [ 0.0588, -0.5908, -0.0550,  ..., -1.2341, -0.6915, -1.2139],
        ...,
        [ 0.5627,  0.0634,  0.5140,  ...,  0.5759, -0.3785, -1.0715],
        [-0.1394,  0.5696, -0.1844,  ..., -0.7985, -0.7111, -0.7317],
        [-0.8557, -0.5214, -0.8404,  ..., -0.2914, -0.1666,  1.7520]],
       dtype=torch.float64)

In [14]:
x_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

### Defining the model


In [16]:
class MySimpleNN():
  def __init__ (self , x):
    self.weight = torch.rand(x.shape[1] , 1, dtype= torch.float64 , requires_grad=True)
    self.bias = torch.zeros(1 , dtype= torch.float64 , requires_grad=True)



  def forward(self, x):
    z = torch.matmul(x, self.weight) + self.bias
    y_pred =  torch.sigmoid(z)
    return y_pred


  def loss_function(self , y_pred , y):

    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1  - y_train_tensor) * torch.log(1 - y_pred)).mean()

    return loss

### Important Parameters

In [17]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [18]:
# Create the model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(x_train_tensor)


  # loss calculate
  loss = model.loss_function(y_pred , y_train_tensor)


  # backward pass

  loss.backward()

  # update parameters
  with torch.no_grad():
    model.weight -= learning_rate * model.weight.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weight.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print( f'Epoch : {epoch + 1} , Loss : {loss.item()}')


Epoch : 1 , Loss : 3.2077259264055478
Epoch : 2 , Loss : 3.076244218804109
Epoch : 3 , Loss : 2.9406386745470305
Epoch : 4 , Loss : 2.8016773897231855
Epoch : 5 , Loss : 2.664048157967721
Epoch : 6 , Loss : 2.5223496802253447
Epoch : 7 , Loss : 2.382335075327186
Epoch : 8 , Loss : 2.2388908277280715
Epoch : 9 , Loss : 2.095714011627263
Epoch : 10 , Loss : 1.9528984410732564
Epoch : 11 , Loss : 1.8172732092888786
Epoch : 12 , Loss : 1.689689701756913
Epoch : 13 , Loss : 1.5699569039819354
Epoch : 14 , Loss : 1.4541708428771232
Epoch : 15 , Loss : 1.3496235911724617
Epoch : 16 , Loss : 1.2570139040156203
Epoch : 17 , Loss : 1.1764902904869974
Epoch : 18 , Loss : 1.1075233536912492
Epoch : 19 , Loss : 1.0489779844151457
Epoch : 20 , Loss : 0.9994351029069415
Epoch : 21 , Loss : 0.9575188877756687
Epoch : 22 , Loss : 0.9220162148872773
Epoch : 23 , Loss : 0.8918838189267775
Epoch : 24 , Loss : 0.8662356756185698
Epoch : 25 , Loss : 0.8443289301948311


In [19]:
model.weight

tensor([[ 0.2724],
        [ 0.1848],
        [-0.0146],
        [-0.1186],
        [ 0.2901],
        [-0.0584],
        [-0.3664],
        [ 0.0721],
        [ 0.2599],
        [ 0.3646],
        [-0.1987],
        [ 0.6288],
        [-0.3479],
        [-0.0735],
        [ 0.2521],
        [ 0.1266],
        [-0.0205],
        [ 0.1742],
        [ 0.1619],
        [ 0.1077],
        [ 0.4093],
        [ 0.0890],
        [ 0.0117],
        [ 0.1300],
        [ 0.2175],
        [-0.3890],
        [ 0.4099],
        [-0.3526],
        [-0.1602],
        [-0.1418]], dtype=torch.float64, requires_grad=True)

In [20]:
model.bias

tensor([-0.1803], dtype=torch.float64, requires_grad=True)

### model evaluation

In [24]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float() # here basically we are scaling the predicted value to either 0 or 1 as we have only 0 and 1 in the (y real) test data
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy : {accuracy}')


Accuracy : 0.5420129299163818
